import "../styles/globals.css";

import type { Metadata } from "next";

import { Providers } from "@/components/providers";
import { geistMono, ibmPlexSans } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ibmPlexSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="max-w-screen overflow-x-hidden px-2">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
